TeachersApp/config/routes.rb
Rails.application.routes.draw do

  root 'teachers#index'
  resources :teachers, only: [:index, :new, :create, :edit, :update, :destroy]
  get 'teachers/:sort_type' => 'teachers#index'

end

TeachersApp/app/models/subject.rb
class Subject < ActiveRecord::Base
	belongs_to :teacher
end

TeachersApp/app/models/teacher.rb
class Teacher < ActiveRecord::Base

	has_many :subjects, dependent: :destroy
	accepts_nested_attributes_for :subjects
	 # reject_if: proc { |attributes| attributes['subject_name'].blank? }

	def active_subjects
		subjects.select { |s| s.active == true }.length
	end

end

TeachersApp/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

TeachersApp/app/controllers/teachers_controller.rb
class TeachersController < ApplicationController

  def index
  	@teachers = Teacher.all
    if params[:sort_type].present?
      if params[:sort_type].eql? "name"
        @teachers = @teachers.sort_by { |t| t.name }
      else
        @teachers = @teachers.sort_by { |t| t.active_subjects }.reverse
      end
    end
  end

  def new
  	@teacher = Teacher.new
    6.times { @teacher.subjects.build }
  end

  def create
  	@teacher = Teacher.new teacher_params
    if @teacher.save
      flash[:notice] = 'Your awesome teacher was created!'
      redirect_to root_path
    else
      flash[:error] = 'Mmm... looks like something went wrong!'
      redirect_to :back
    end
  end

  def edit
    @teacher = Teacher.find(params[:id])
  end

  def update
    @teacher = Teacher.find(params[:id])
    if @teacher.update_attributes(teacher_params)
      flash[:notice] = 'Your teacher was updated!'
      redirect_to root_path
    else
      flash[:error] = 'Mmm... looks like something went wrong!'
      redirect_to :back
    end 
  end

  def destroy
    if Teacher.destroy(params[:id])
      flash[:notice] = 'The teacher was destroyed!'
      redirect_to root_path
    else
      flash[:error] = 'Mmm... looks like something went wrong!'
      redirect_to back
    end
  end

  def teacher_params
  	params.require(:teacher).permit(:name, :code, subjects_attributes: [:id, :subject_name, :subject_id, :active])
  end
end

TeachersApp/app/helpers/application_helper.rb
module ApplicationHelper

	def flash_class(level)
	  case level
	     when 'notice' then "alert alert-success"
	     when 'error' then "alert alert-danger"
	  end
	end

end

TeachersApp/app/helpers/teachers_helper.rb
module TeachersHelper
end

TeachersApp/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TeachersApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="jumbotron">
  <h1>teacher<b>App</b></h1>
  <p>Welcome to the <b>greatest</b> teachers app!</p>
</div>

<% flash.each do |name, message| %>
  <div class="<%= flash_class(name) %>">
    <%= message %>
  </div>
<% end %>

<b>
  <ul class="nav nav-pills">
    <li><%= link_to 'Home',  teachers_path %></li>
    <li><%= link_to 'New Teacher',  new_teacher_path %></li>
  </ul>
</b>

<%= yield %>

</body>
</html>

TeachersApp/app/views/teachers/edit.html.erb
<h1>Edit an awesome teacher!</h1>
<h2><b><%= @teacher.name + " | " + @teacher.code.to_s %> </b></h2>
<div class="row">
  <div class="col-md-5">
    <%= form_for @teacher, { role: 'form' } do |f| %>

      <%= f.fields_for :subjects, @teacher.subjects do |builder| %>

        <%= builder.label :subject_name, "Subject_name" %>
        <%= builder.text_field :subject_name %>

        <%= builder.label :subject_id, "Subject ID" %>
        <%= builder.number_field :subject_id %>

        <%= builder.label :active, "Active" %>
        <%= builder.check_box :active %>
        
        <br />

      <% end %>

     <%= f.submit 'Update teacher', { class: 'btn btn-success' } %>

    <% end %>
  </div>
</div>

TeachersApp/app/views/teachers/index.html.erb
<h1> Teacher's List </h1>
<a href="<%= teachers_path + '/active' %>" class="btn btn-primary" role="button" >Sort by Active Subjects</a>
<a href="<%= teachers_path + '/name' %>" class="btn btn-primary" role="button" >Sort by Name</a>

<table class="table table-striped">
  <tr>
    <th width="100">Name</th>
    <th width="100">Code</th>
    <th width="100">Active Subjects</th>
    <th width="100" colspan="3">Actions</th>
  </tr>
    <% for t in @teachers %>
      <tr>
        <td><%= t.name %> </td>
        <td><%= t.code %> </td>
        <td><%= t.active_subjects %></td>
        <td width="55"><%= link_to 'Edit', edit_teacher_path(t) %></td>
        <td><%= link_to 'Delete', t, :method => 'delete' %></td>
      </tr>
    <% end %>
</table>
<br />

TeachersApp/app/views/teachers/new.html.erb
<h1> Create an awesome Teacher </h1>
<div class="row">
  <div class="col-md-5">
    <%= form_for @teacher, { role: 'form' } do |f| %>

      <%= f.label :name, "Name" %>
      <%= f.text_field :name, { class: 'form-control' } %>
      <br />

      <%= f.label :code, "Code" %>
      <%= f.number_field :code, { class: 'form-control' } %>
      <br />
      
      <%= f.fields_for :subjects do |builder| %>

        <%= builder.label :subject_name, "Subject_name" %>
        <%= builder.text_field :subject_name %>

        <%= builder.label :subject_id, "Subject ID" %>
        <%= builder.number_field :subject_id %>

        <%= builder.label :active, "Active" %>
        <%= builder.check_box :active %>
        <br />

      <% end %>


     <%= f.submit 'Add teacher', { class: 'btn btn-success' } %>

    <% end %>
  </div>
</div>